// export const COURSES_API_URL = "https://wbdv-generic-server.herokuapp.com/api/001358744/courses";
export const COURSES_API_URL = "http://localhost:8080/api/courses";
// export const MODULES_API_URL = "https://wbdv-generic-server.herokuapp.com/api/001358744/modules";
export const MODULES_API_URL = "http://localhost:8080/api/modules";
//export const LESSONS_API_URL = "https://wbdv-generic-server.herokuapp.com/api/001358744/lessons";
export const LESSONS_API_URL = "http://localhost:8080/api/lessons";
// export const TOPICS_API_URL = "https://wbdv-generic-server.herokuapp.com/api/001358744/topics";
export const TOPICS_API_URL = "http://localhost:8080/api/topics";
// export const TOPICS_API_URL = "https://wbdv-generic-server.herokuapp.com/api/001358744/topics";
export const WIDGETS_API_URL = "http://localhost:8080/api/widgets";
//export const COURSES_MODULES_API_URL = (courseId) => `https://wbdv-generic-server.herokuapp.com/api/001358744/courses/${courseId}/modules`;
export const COURSES_MODULES_API_URL = (courseId) => `http://localhost:8080/api/courses/${courseId}/modules`;
//export const MODULES_LESSONS_API_URL = (moduleId) => `https://wbdv-generic-server.herokuapp.com/api/001358744/modules/${moduleId}/lessons`;
export const MODULES_LESSONS_API_URL = (moduleId) => `http://localhost:8080/api/modules/${moduleId}/lessons`;
// export const LESSONS_TOPICS_API_URL = (lessonId) => `https://wbdv-generic-server.herokuapp.com/api/001358744/lessons/${lessonId}/topics`;
export const LESSONS_TOPICS_API_URL = (lessonId) => `http://localhost:8080/api/lessons/${lessonId}/topics`;
//export const LESSONS_TOPICS_API_URL = (lessonId) => `http://localhost:8080/api/lessons/${lessonId}/topics`;
export const TOPICS_WIDGETS_API_URL = (topicId) => `http://localhost:8080/api/topics/${topicId}/widgets`;
